### ISSUE TITLE
Handle Module:Function tags

### ISSUE THREAD

**Issue by evnu** [syed/erlcscope#7]
Currently, when searching for a function, the user cannot search for `Module:Function`, but only for `Function`. That is a problem if the function name is a common one. Then, the user has to search a list of functions to find the right file. `erlcscope` could be extended to add two tags for a function, one as it is done as of now, and one with `Module:` prepended. This is how [vim-erlang-tags](https://github.com/vim-erlang/vim-erlang-tags) works around this issue with `ctags`.

From the [README.md](https://github.com/vim-erlang/vim-erlang-tags/blob/master/README.md) of `vim-erlang-tags`:

> When using Exuberant ctags or etags, the genereted tags will contain function names, but there will be no module:function tags. This is a problem because if several functions (in different modules) have the same name, the text editor will not know which one to jump to.

I think this would be a useful addition here as well. Would you be interested in this? I think I could come up with a pull request.

**Comment by syed** [comment]
Yes. I think this would be a very good functionality to have. Please open a PR I'll be happy to review and merge

**Comment by evnu** [comment]
I started working on this in [a new branch](https://github.com/evnu/erlcscope/tree/handle-module-function). Alas, `cscope` does not allow searching for `Module:Function`, as this symbol does not adhere to the C naming requirements of a symbol. The error message when searching for `erlcscope:start_link` is `This is not a C symbol: erlcscope:start_link`. I also tried to use `$` as a separator (it seemed to be an allowed character according to [scanner.l](https://searchcode.com/codesearch/view/20547522/)), but could not properly search for symbols with that either.

One work-around could be to prepend the module using `Module_Function`. Of course, there could be name clashes. To avoid name clashes, `_Module_Function` would be possible as well. Erlang disallows `_` as the first character of an atom, except if the atom is wrapped in quotes. So again, this work-around does not work in certain cases, which makes it a crutch in the long run.

Hence, I will close this issue. It seems that there is no good way to bend `cscope` into allowing this functionality. If somebody comes up with a nicer approach, I'd be willing to pick up the work again.

**Comment by evnu** [comment]
Just to add another point to this issue: I tried to use cscope within vim to search for `Module:Function` as well. Vim does not complain about the symbol not being a C symbol, but it also did not find the declaration.

**Comment by syed** [comment]
Yeah. I remember from long time trying to add the module functionality and running into the same issue. At that time I did not bother to explore further as I wanted to finish the basic functionality first. The problem now is that in vim you will have to search for `Module$Function` as opposed to `Module:Function` which kept me from going deeper.

**Comment by evnu** [comment]
Searching for `Module$Function` would be OK in my opinion, as that translation can be done within a mapping. But there is still a mismatch between using the cscope interface and vim, which is undesirable.
